import { Router } from "express";
import { protect, authorize } from "../middleware/authMiddleware.js";
import { applyForJob, getMyApplications, getJobApplicants, updateApplicationStatus, withdrawApplication } from "../controllers/applicationController.js";
const router = Router();
router.post("/job/:jobId", protect, authorize("student"), applyForJob);
router.get("/my", protect, authorize("student"), getMyApplications);
router.get("/job/:jobId", protect, authorize("recruiter"), getJobApplicants);
router.patch("/:id/status", protect, authorize("recruiter"), updateApplicationStatus);
router.patch("/:id/withdraw", protect, authorize("student"), withdrawApplication);
export default router;
